# config/packages/doctrine_migrations.yaml


doctrine_migrations:
  # List of namespace/path pairs to search for migrations, at least one required
  migrations_paths:
    'MyHotels\Migrations': '%kernel.project_dir%/src/Infrastructure/Persistence/MySql/Migrations'
