doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            Core_Hotel:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/Core/Infrastructure/Persistence/MySql/Mapping/Hotel'
                prefix: 'MyHotels\Core\Domain\Model\Hotel'
            Core_Room:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/Core/Infrastructure/Persistence/MySql/Mapping/Room'
                prefix: 'MyHotels\Core\Domain\Model\Room'
            Core_Booking:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/Core/Infrastructure/Persistence/MySql/Mapping/Booking'
                prefix: 'MyHotels\Core\Domain\Model\Booking'